#!/usr/bin/env bash

set -e

help() {
  cat << HELP

  USAGE: sinatra-gen [options] PROJECT_NAME

  OPTIONS:
    -h, --help      Display this help.
    -d, --dry-run   Don't actually create any files.

HELP
}

red=$(printf "\033[31m")
clr=$(printf "\033[m")

if [[ -z "$*" ]]; then
  help
  exit
fi

while [[ "$1" == -* ]]; do
  case "$1" in
    -h|--help)
      help
      exit;;
    -*)
      echo "  ${red}ERROR: UNKNOWN ARGUMENT ($1)${clr}"
      help
      exit 1;;
  esac
done
