#!/usr/bin/env bash

set -e

help() {
  cat << HELP

  USAGE: sinatra-gen [options] PROJECT_NAME

  OPTIONS:
    -h, --help      Display this help.
    -d, --dry-run   Don't actually create any files.
    -t, --template  Specify a template engine to use. Default is
                    Mustache; optionally use ERB, Haml, or Slim.
    -s, --style     Specify a stylesheet preprocessor. Default is
                    Scss; optionally use Sass or LESS.

HELP
}

if [[ -z "$*" ]]; then
  help
  exit 0
fi

while [[ "$1" == -* ]]; do
  case "$1" in
    -h|--help)
      help
      exit;;
    -*)
      echo ""
      echo "  UNKNOWN ARGUMENT."
      help
      exit 1;;
  esac
done
